// Generated by Wrangler by running `wrangler types --env example`

interface Env {
	PERMIT_PDP_URL: string | undefined;
	PERMIT_API_KEY: string | undefined;
	OAUTH_KV: KVNamespace;
	WORKOS_CLIENT_ID: string;
	WORKOS_CLIENT_SECRET: string;
	MCP_OBJECT: DurableObjectNamespace /* MyMCP */;
	AI: Ai;
}
